### ISSUE TITLE
Why limit the version of nodes when downloading dependencies？

### ISSUE THREAD

**Issue by melodyWxy** [reach/router#362] opened 2020-02-25 03:21 UTC
## Think you found a bug?

When I enter this directory  —   /examples/crud/ ,      then running `yarn ` ; 

I try to choose any version of reach/router ，but it's all a mistake  —  `error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.16.0"`

In fact, I don't think I should adjust my node version, because more people use 12.16.1.

I think this case is trying to dissuade me when I want to explore reach/router.

So, maybe we can make it compatible with a higher version of the node environment?

**Comment by blainekasten** [comment] 2020-02-27 20:18
@melodyWxy this isn't due to our library. This is from the `upath` dependency. Also largely these are just warnings and not actual issues. The only thing we could do here is to update the `upath` dependency. Feel free to do that if you want!

I'm going to close this issue for now as it's not a bug with the router. Thanks for the report!

**Closed by blainekasten** 2020-02-27 20:18 UTC
