### ISSUE TITLE
Case insensitive routes

### ISSUE THREAD

**Issue by epignosisx** [reach/router#127] opened 2018-08-13 18:35 UTC
Looks like routes are case sensitive. So one of these two will not be a match "/Dashboard" and "/dashboard". Take a look at: https://codesandbox.io/s/z2qw8zykmp

Not sure if this was a design decision or should this be considered a bug?

**Comment by clechner77** [comment] 2018-10-30 03:39
Yes, this bit me today too.  Basename is case sensitive and it gave me a bit of a headache today.

**Comment by chiester** [comment] 2019-03-06 00:23
+1

**Comment by r1cs1** [comment] 2019-03-09 16:36
Is there any update on this?

**Comment by clechner77** [comment] 2019-03-12 02:20
This is one of those things that I really hope gets looked at.  At the very least, perhaps it could be an option only.

**Comment by mupkoo** [comment] 2019-03-17 17:37
To me it is clear that `/Dashboard` and `/dashboard` can be two different pages, and even Google will treat them as such. And I think that it is expected behaviour and one that can found in other tool like Rails and Ember.js

**Comment by millette** [comment] 2019-03-17 19:18
They can be different, but arean't always, example: https://github.com/reAch/Router

**Comment by ryanflorence** [comment] 2019-09-05 04:47
Hmm, everything after the TLD has historically been case sensitive since it's originally based on file systems.

I can see the desire to be case insensitive, and maybe that's the right thing today in a modern client-side router, but I'm going to close this issue to avoid introducing something that might make the merging of React Router and @reach/router harder.

We'll consider it over there in the future :)

For context: https://reacttraining.com/blog/reach-react-router-future/

**Closed by ryanflorence** 2019-09-05 04:47 UTC

**Comment by akshayrathodar** [comment] 2023-11-30 07:27
Yes, this needs to be resolve. Any Update ?
