### ISSUE TITLE
Page renders twice when using CSSTransition

### ISSUE THREAD

**Issue by jvitela** [reach/router#258] opened 2019-04-02 23:26 UTC
**Bug**

In the animation example, adding a *Link* component inside a *Page* component causes the exiting page to render again.

Can be reproduced here: https://codesandbox.io/s/reach-router-starter-v1-yybhi
Check the console to see the calls to Page::render

**Comment by jvitela** [comment] 2019-07-12 08:23
Hi @dralletje and @ryanflorence,

Is this project still maintained? I opened this issue more than 3 months ago and there is still no reply or comment.

At work, we were planning to replace our current router from [react-router|https://reacttraining.com/react-router/web] to **reach/router** but if this project is not longer maintained I rather stay with the current one or search for better alternatives.

I hope you can spare a few minutes to drop a comment here.

**Comment by xBATx** [comment] 2019-08-19 22:52
Hi guys, 

any updates on this? I saw my component rendered twice with higher timeouts - visibility issue had gone after adding `exit={false}` to `<CSSTransition>` as mentioned in [react-transition-group issue](https://github.com/reactjs/react-transition-group/issues/213) but I'm still experiencing problems with double mounting of components as mentioned in the ticket description. 
Do you have any suggestion how to prevent this behaviour?

**Comment by mtliendo** [comment] 2019-09-10 21:13
This seems to have been an issue with react-transition-group.  I reviewed the sandbox and updated to the latest version (4.3.0) and it no longer rerendered the page twice.  

If the issue is still happening after upgrading, feel free to comment and I'll reopen, closing for now.

**Closed by mtliendo** 2019-09-10 21:13 UTC
