### ISSUE TITLE
Redirect does not find subpath when noThrow

### ISSUE THREAD

**Issue by AlanChauchet** [reach/router#47] opened 2018-06-07 08:28 UTC
Hi,

My router component looks like this

```
class MainRouter extends PureComponent {
  render() {
    return (
      <Router>
        <Base path="/">
          <Redirect from="/" to="signIn" noThrow />
          <SignIn path="signIn" />
          <SignUp path="signUp" />
          <ConfirmEmail path="confirmEmail" />
        </Base>
      </Router>
    );
  }
}
```

I can navigate to `/signIn` and my SignIn component correctly renders as a child of my Base component.
If I navigate to the root `/`, I can see that the redirection changes my url from `/` to `/signIn`, my Base component renders but my SignIn component does not. I have to manually refresh the page to see the component appear.
If I remove the `noThrow` prop from the Redirect, everything works as expected (but I would prefer not to have an exception thrown).
My Base component always renders its children so I don't think it is related to that component.

Is there anything I am doing wrong ?

**Comment by ryanflorence** [comment] 2018-06-07 16:22
Thanks, closing as duplicate of #46

**Closed by ryanflorence** 2018-06-07 16:22 UTC
