### ISSUE TITLE
Link getProps with react-dom 16, warning: Invalid attribute name

### ISSUE THREAD

**Issue by fred-king** [reach/router#324] opened 2019-11-14 19:44 UTC
## Link getProps throws warnings ##
Using getProps in Link results in console warnings in development for react-dom "Warning: Invalid attribute name: `0`"

Replicated here:

https://codesandbox.io/s/reach-router-starter-v1-14hk7

React-dom 16+ allows for arbitrary attributes, however this warning is at a minimum annoying and triggers testers. 

Any advice?

**Comment by blainekasten** [comment] 2019-11-22 17:06
@fred-king this is because when `isPartiallyCurrent` is false, you are returning a string instead of an object. Props have to be an object. 

I'm going to close this issue as it's not a bug with the router. The only action item I could see here would be to log a warning if a user passes a type different than `{} | null`. If you think that would be beneficial, feel free to submit a PR!

**Closed by blainekasten** 2019-11-22 17:06 UTC
Labels: invalid
