### ISSUE TITLE
redirectTo not redirect and throw error

### ISSUE THREAD

**Issue by popuguytheparrot** [reach/router#100] opened 2018-07-17 21:52 UTC
in App i try redirect to login page anon user

```
componentDidMount() {
    const { isAuthenticated } = this.props;
    if (!isAuthenticated) redirectTo('/login');
  }

```
in console i have 

```
 Uncaught RedirectRequest {uri: "/login"}
The above error occurred in the <App> component:
    in App (created by Connect(App))
    in Connect(App)
    in MuiThemeProvider
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

How to use redirect right and fix this

**Comment by chooban** [comment] 2018-07-19 10:01
Possibly related to #91.

**Comment by deadcoder0904** [comment] 2018-07-31 10:14
I'm having the same issue & I'm also using `<Redirect to="/login" />` route like

```js
render() {
  if (!isAuthenticated) return <Redirect to="/login" />;
}
```

How to solve this same issue? /cc @ryanflorence

**Comment by deadcoder0904** [comment] 2018-08-15 05:30
I switched to `react-router`. Although this API is much easier, few things like Hash Router won't be supported & the workaround has lot of code & there will be few errors as its in its early stages. So I switched. You can if you want to. It won't require a lot of code to switch other than 4-5 lines extra till this thing gets solved.

**Comment by Popugune** [comment] 2018-08-15 07:14
@deadcoder0904 i fixed it with navigate() `!isAuthenticated && navigate('/login');`

**Comment by chasemccoy** [comment] 2018-08-15 15:06
@Popugune Unfortunately `navigate()` has the same issue for me. 

@deadcoder0904 I can't switch to React Router as I'm using Gatsby v2 which uses Reach Router internally.

**Comment by chasemccoy** [comment] 2018-08-15 15:25
I want to stay on the latest version.

**Comment by littlemooon** [comment] 2018-08-20 13:14
Using latest gatsby v2 as well. Ive had to create a Redirect component with timeout:

```javascript
class Redirect extends Component {
  static propTypes = {
    to: PropTypes.string.isRequired,
    navigate: PropTypes.func.isRequired,
  };

  componentDidMount() {
    setTimeout(() => this.props.navigate(this.props.to, { replace: true }), 0);
  }

  render() {
    return null;
  }
}
```

**Comment by 416serg** [comment] 2018-08-21 20:44
I would still like to get `<Redirect>` to work as expected

Right now I get `Uncaught RedirectRequest {uri: "/login"}`

Authenticated HOC
```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Redirect } from '@reach/router';

class Authenticated extends React.Component {
  render() {
    const { authenticated, children } = this.props;

    return authenticated ? <React.Fragment>{children}</React.Fragment> : <Redirect to="/login" />;
  }
}

Authenticated.propTypes = {
  children: PropTypes.node.isRequired,
  authenticated: PropTypes.bool.isRequired,
};

export default Authenticated;
```

Router
```jsx
<Router>
  <Authenticated path="profile" {...props}>
    <Profile path="/" {...props} />
    <NotFound default />
  </Authenticated>
</Router>
```

**Comment by cdock1029** [comment] 2018-08-23 14:02
Throwing an error on redirect is intended behavior, and explained in the docs:

https://reach.tech/router/api/Redirect

> Redirect works with `componentDidCatch` to prevent the tree from rendering and starts over with a new location.

> Because React doesn’t swallow the error this might bother you. For example, a redirect will trigger Create React App’s error overlay. In production, everything is fine. If it bothers you, add `noThrow` and Redirect will do redirect without using componentDidCatch.

> If you’re using React < 16 Redirect will not throw at all, regardless of what value you put for this prop.

> If you’re using componentDidCatch in your app please read the `isRedirect` doc!

### `noThrow`
> 
```jsx
<Redirect noThrow />
```

**Comment by chasemccoy** [comment] 2018-08-23 15:27
@cdock1029 I was having this issue even when using the `noThrow` prop, but I will double check that again.

**Comment by popugune** [comment] 2018-09-06 09:07
@ryanflorence look please

**Comment by fa7ad** [comment] 2018-10-01 20:55
hey, so the issue is still there. any solutions?

**Comment by ArthurYidi** [comment] 2018-10-06 19:12
If you are doing a redirect (for a login page) use:
`<Redirect  from="" to="" noThrow />`

Alternatively use `navigate('')`

The Gatsby examples need to be updated.

**Comment by kbrgl** [comment] 2018-10-12 10:32
Having this issue on a fresh create-react-app install as well.

I tried `<Redirect to="/" />` as well as redirectTo(), the only way it works is with `setTimeout(..., 0)`.

**Comment by detj** [comment] 2019-06-13 21:18
Well, I read the above comments. Not really sure how to use `redirectTo` in a way that it does not throw & actually redirects.

The [redirectTo doc](https://reach.tech/router/api/redirectTo) does not help. Also, the doc says uri must be absolute, but the example uses a relative path. 😕

**Comment by yoDon** [comment] 2019-07-05 22:38
Like @detj I find [redirectTo doc](https://reach.tech/router/api/redirectTo) to have zero guidance on how to make this work. I ended up using navigate (`import { navigate } from "@reach/router";` ) as a workaround.

**Comment by detj** [comment] 2019-07-06 09:55
I used `navigate` as a workaround too.

**Comment by jedmao** [comment] 2019-08-22 19:20
For anyone struggling about how to write tests against `Redirect` w/o throwing errors, I hope this helps you:

```ts
it('redirects from "/" to "/foo"', async () => {
	const spy = jest.spyOn(console, 'error').mockImplementation(() => {})

	render({ route: '/' })

	await wait(() => {
		expect(document.title).toBe('Home')
	})

	spy.mockRestore()
})
```

**Comment by mtliendo** [comment] 2019-09-12 05:35
As mentioned, `<Redirect from="" to="" noThrow />` will solves for the error being thrown 😊

**Closed by mtliendo** 2019-09-12 05:35 UTC

**Comment by ashnur** [comment] 2019-10-24 11:46
redirectTo throws error and doesn't navigate with ErrorBoundary even. The error is caught but that doesn't help, everything is unmounted anyway.

**Comment by arhoy** [comment] 2019-11-18 08:30
Thank you @cdock1029 .
I have the following in my login.js file
```
  // redirect if authenticated.
  if (isAuthenticated) return <Redirect to="/app" noThrow />;
```

adding noThrow doesn't cause app to crash after the user login and redirect to the app page

**Comment by ashnur** [comment] 2019-11-18 12:45
very declarative

**Comment by jsfour** [comment] 2020-12-30 02:20
We had a similar issue only we had issues using the `Redirect` component as well as the `navigate` and `redirectTo`functions when sending from a reach routed component to a static page on gatsby.

The solution was to just use `window.location` inside of an effect hook. It looked similar to this:

```javascript
  const [shouldRedirect, setShouldRedirect] = useState();
  const [linkTo, setLinkTo] = useState("/some/location");
  const handleClick = () => {
    setShouldRedirect(true);
  };

  useEffect(() => {
    if (shouldRedirect && linkTo) {
      window.location.replace(linkTo);
    }
  }, [shouldRedirect]);

```
