### ISSUE TITLE
Preact Support?

### ISSUE THREAD

**Issue by JayKan** [reach/router#9] opened 2018-06-01 01:58 UTC
Are there any examples on how to integrate with Preact + SSR?

**Comment by Kocisov** [comment] 2018-06-01 08:19
It works with `preact-compat`

```js
import { Component } from 'preact'
import { Router } from '@reach/router'

const Color = () => (
  <div>
    <h2 style={{ color: 'yellow' }}>Yellow</h2>
  </div>
)

export default class App extends Component {
  render() {
    return (
      <div>
        <h1>Hello, World!</h1>
        <Router>
          <Color path="/" />
        </Router>
      </div>
    )
  }
}

```

**Comment by ryanflorence** [comment] 2018-06-01 15:00
👆what they said :)

**Comment by hipstersmoothie** [comment] 2018-06-09 03:06
@ryanflorence I got this working with webpack. When I switching webpack to `production` the build breaks. [Example](https://github.com/hipstersmoothie/preact-reach-router-webpack-example)

**Comment by mfarhadpur** [comment] 2018-06-09 05:19
@Kocisov Does that work with the Link component as well? I get a `value is not a function` TypeError.

**Comment by Kocisov** [comment] 2018-06-09 09:43
As I am not using Preact, I pretty much know nothing about this.

Sorry.

**Comment by hipstersmoothie** [comment] 2018-06-09 16:47
Info is more for @ryanflorence 😜

**Comment by hipstersmoothie** [comment] 2018-06-09 18:39
Confirmed adding these lines to my repo:

```js
const App = () => (
  <div id="foo">
    <span>Hello, world!</span>
    <Link to="/" />
  </div>
);
```

breaks the development build with this error:

```
Uncaught TypeError: value is not a function
    at setAccessor (preact.esm.js:262)
    at diffAttributes (preact.esm.js:605)
    at idiff (preact.esm.js:451)
    at diff (preact.esm.js:356)
    at renderComponent (preact.esm.js:777)
    at renderComponent (preact.esm.js:762)
    at renderComponent (preact.esm.js:762)
    at renderComponent (preact.esm.js:762)
    at setComponentProps (preact.esm.js:684)
    at buildComponentFromVNode (preact.esm.js:864)
```

**Comment by ryanflorence** [comment] 2018-06-09 19:27
I’d love to support preact but I won’t be spending time on debugging this, anybody want to dig in?

**Comment by ryanflorence** [comment] 2018-06-09 19:36
What happens if you have text in the link?

**Comment by mfarhadpur** [comment] 2018-06-09 19:48
> What happens if you have text in the link?

Same issue. Here's the basic example from the docs with preact-compat: https://codesandbox.io/s/9jpv93q9nr

**Comment by developit** [comment] 2018-06-09 19:48
I believe the issue is that there is a `value` property on `anchorProps` here, which is then being applied to the `<a>` erroneously:
https://github.com/reach/router/blob/7d0cf57e73cb4fd5043e8fd0ddeb387dd886c3f7/src/index.js#L372

**Comment by developit** [comment] 2018-06-09 19:55
Ah nevermind, it's refs. `react-create-ref` doesn't work with Preact right now I guess.

**Comment by hipstersmoothie** [comment] 2018-06-09 20:27
So it's the `forwardRef` code that's probably the issue?

**Comment by hipstersmoothie** [comment] 2018-06-09 20:30
@developit is there an issue tracking this in https://github.com/developit/preact?

**Comment by developit** [comment] 2018-06-09 21:11
Alright, I just implemented createRef in preact (core):
https://github.com/developit/preact/pull/1138

If that lands, all is well. Otherwise we'll add it to `preact-compat` since reach/router requires compat anyway.

**Comment by developit** [comment] 2018-06-09 21:15
I guess that's part of it, but really it's that `create-react-ref` returns an object, which when passed as `<foo ref={ {} } />` is not currently supported in Preact. That feature of React was only released in the most recent version, and we're still working out whether it's something that should be in Preact's core, or in compat.

**Comment by ryanflorence** [comment] 2018-06-09 22:07
This project doesn’t use createRef directly, is it happening indirectly or is this just a problem for the app using it? Closing unless there’s an action item here. Thanks!

**Closed by ryanflorence** 2018-06-09 22:07 UTC

**Comment by alexkhismatulin** [comment] 2019-05-20 12:20
> Does it work now? :)

Yeah, check it out in sandbox mentioned above by installing new version of `preact`: https://codesandbox.io/s/9jpv93q9nr
