### ISSUE TITLE
documentation for navigate "option - state" is wrong

### ISSUE THREAD

**Issue by SamMaxwell** [reach/router#321] opened 2019-11-05 14:15 UTC
the value is passed incorrectly navigate("/todos", { newId: id }), should be changed to navigate("/todos", { state: { newId: id } })

there is disagreement about the name of the value passed into location state. the code that calls navigate names it "newId", the the code that uses it thinks it is named "id". I assume the value should be named "id"

so the caller should be changed to navigate("/todos", { state: { id } })

**Comment by blainekasten** [comment] 2019-11-22 17:08
@SamMaxwell thanks for the report! Are you happy to contribute this fix?

**Comment by dmudro** [comment] 2020-01-26 14:24
I bumped into the same issue when implementing `navigate()` based on the doc site on https://reach.tech/router/api/navigate.

In addition to newId / id mismatch, the doc site also lacks `state` property in the options object in the code example

`navigate("/todos", { newId: id })`

I assume it should be:

`navigate("/todos", { state: { newId: id } })`

Both issues seem to have been fixed for a while in the source: https://github.com/reach/router/blob/master/website/src/markdown/api/navigate.md

@blainekasten perhaps the latest doc needs to be deployed? The current one on https://reach.tech/router does indeed say v1.1.0 in the page header which is a fairly old version.

**Comment by blainekasten** [comment] 2020-01-27 20:30
Word. I'll get a new version out soon and talk to Ryan about getting the site updated. Thanks for the advice 👍

**Comment by xu3u4** [comment] 2020-02-28 05:59
I think this issue is fixed and can be closed? https://reach.tech/router/api/navigate

**Comment by jacekk** [comment] 2020-03-18 09:31
Isn't this issue a duplicate of https://github.com/reach/router/issues/96 ??

@blainekasten has fixed and marked the #96 issue as done at Feb 14th. This issue was reported before. I think this is a duplicate.

**Closed** 2020-03-19 14:39 UTC
Labels: good first issue
