### ISSUE TITLE
Implementing "Back" functionality

### ISSUE THREAD

**Issue by ShMcK** [reach/router#44] opened 2018-06-06 00:13 UTC
**Question**

How is "go back to the previous route" functionality handled in Reach Router?

**Comment by taurose** [comment] 2018-06-06 21:44
As far as I can tell there's nothing built in. Since it uses history API, you can always do `window.history.back()` or `window.history.go(-1)` , however.

**Comment by ryanflorence** [comment] 2018-06-07 16:56
Yep, that should work just fine.

**Comment by ShMcK** [comment] 2018-06-07 20:46
`window.history.back()` would be an elegant solution. In practice, it doesn't seem to be currently working.

```
// traversing routes
A => B => C

// calling window.history.back() from C
// expected B
// actual A
```

**Comment by ryanflorence** [comment] 2018-06-11 20:01
Anybody wanna implement this?

- If it's an int, call history.go(n)
- if it's not, carry on
- can probably skip the `transitioning` checks because those are just there to prevent extra items being added to the stack, with `go` we're just moving around in the stack.

**Comment by doasync** [comment] 2018-07-10 21:16
Using `window.history.back()` your users can leave the app, `navigate(-1)` should prevent that

**Comment by dydokamil** [comment] 2018-08-18 17:14
Is it a good practice to use the `window` variable?

**Comment by bogas04** [comment] 2018-09-07 05:32
@dydokamil  There's nothing wrong with using `window` or other browser APIs/Objects. However you need to keep in mind that the code path would get undefined in case it's running on server (Server Side Rendering).

Since going back would usually be triggered by a click event, you can use it safely in the event listener.

**Comment by tylerwray** [comment] 2018-11-04 22:19
Looks like this was never added, do we still want to add something to navigate to make this work? Or should we just encourage people to use the `window.history.back()` api?

**Comment by max-allen** [comment] 2018-11-23 17:13
Currently working on an app that uses reach router and am running into this issue, so just want to raise the topic again since the issue's still open. Is #197 going to be merged in sometime soon?

**Comment by stevematdavies** [comment] 2019-02-07 14:04
Unfortunately, window.history.back() doesn't re render the page that was linked from , so things that need to happen on that page with a render or CDM etc don't work with this method

**Comment by bpurtz** [comment] 2019-07-31 19:10
+1

**Comment by lesmo** [comment] 2019-08-19 07:41
```window.history.back()``` isn't available when using [memorySource](https://github.com/reach/router/blob/1c13f8a96179a896c0f75184b93d1a62dcc4dc70/src/lib/history.js#L69). To prepare this and be independent of the browser (for stuff like Gatsby, maybe?), there should be a way of going back in history without ```window```.

There's [this pull request](https://github.com/reach/router/pull/197) that I think adds this feature properly, but it hasn't been merged. To be completely functional, [memorySource](https://github.com/reach/router/blob/1c13f8a96179a896c0f75184b93d1a62dcc4dc70/src/lib/history.js#L69) must be modified to add the ```history::go()``` method required for this to work.

I'm worried this repository is no longer maintained, though. It'd be a shame. Anyone knows what's up?

**Comment by alias-mac** [comment] 2019-08-20 01:38
I believe your answer can be found in https://reacttraining.com/blog/reach-react-router-future/

**Comment by lesmo** [comment] 2019-08-20 07:08
> I believe your answer can be found in https://reacttraining.com/blog/reach-react-router-future/

Ah! That explains it all. Makes a lot of sense. Perhaps the project should contain some sort of deprecation notice in favor of the new React Router. It could help close a lot of issues regarding new features and whatnot.

Many have no idea about the foreseeable future of @reach. Myself included... until now.

Thanks a lot!

**Comment by ryanflorence** [comment] 2019-09-05 06:22
#197

**Closed by ryanflorence** 2019-09-05 06:22 UTC
Labels: enhancement

**Comment by Xapphire13** [comment] 2019-12-25 03:07
@ryanflorence, this is still broken (even in the beta 1.3.0 version) due to the call to `resolve(...)` here: https://github.com/reach/router/blob/0908a5fd7d8a7d5c928a8062234ce6f5639a1962/src/index.js#L220

`resolve(...)` treats the argument as a string and throws an exception when trying to do a `.substr`

**Comment by gazgump** [comment] 2020-03-03 16:01
import { navigate } from "@reach/router";

const goBack = () => {
     navigate(-1);
}

<a onClick={goBack} className="back-link">Back</a>

**Comment by Xapphire13** [comment] 2020-03-03 16:13
@gazgump, which version have you confirmed this to be working in?

As stated above, there is a bug with how the parameter is being handled.

**Comment by gazgump** [comment] 2020-03-03 16:14
"@reach/router": "^1.3.1",

**Comment by gazgump** [comment] 2020-03-03 16:16
https://reach.tech/router/api/navigate

You can pass a number to go to a previously visited route.

navigate(-1)

**Comment by Xapphire13** [comment] 2020-03-03 16:39
@gazgump, i know what the API docs say. But at least as of 1.3.0, that API was broken. I'll give a newer version a try =], thanks for the heads up.

**Comment by JamesPortelli** [comment] 2020-03-17 16:03
@ryanflorence @gazgump @Xapphire13 I just ran into the same issues on version 1.3.3. I think the issue presents itself when attempting to use -1 with the navigate function passed in as props to the component usually used for relative navigation.

**Comment by realamirhe** [comment] 2021-01-18 10:42
if you are using reach-router in mini-app such as iframe and you don't want to change the parent router, or if you want to store history entries in memory for testing or other platforms like Native and you are using `createMemorySource` non of `navigate(-1)` or `window.history.back()` or `window.history.go(-1)` will work, here is a hacky low-level way to replace navigate for numbers.

```js
const source = createMemorySource('/default')
// will be used in reach-router provider
export const history = createHistory(source)
// will be used for navigation 
export const { navigate } = history
```
till `"@reach/router": "^1.3.4"`, it doesn't provide a method for replacing state when `to` is a number in `navigate(to).

https://github.com/reach/router/blob/e203fe612236851a0bd3c77dba693e539a351c62/src/lib/history.js#L75-L78

here is a low-level hacky usage of reach-router for simulate back, if you are using the above setup

```js
export const dangerouslyGoToLastRoute = async () => {
  try {
    source.history.go(-1)
    const lastRoute = source.history.entries[source.history.index].pathname
    source.history.entries.pop()
    if (lastRoute) await navigate(lastRoute, { replace: true })
  } catch (error) {
    console.log(error)
  }
}

```


### Usage
```jsx
const goToPreviousRoute = dangerouslyGoToLastRoute

const Button = () => (
  <button onClick={goToPreviousRoute} >back</button>
)
```

**Comment by Falci** [comment] 2021-10-15 13:12
```
Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:history.go(-1)".
```
